name: Run Pytest

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set Up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11.11'
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
      - name: Run pytest
        run: |
          pytest test_news
